# Generated by Django 3.2.6 on 2021-11-16 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Übersicht',
                'verbose_name_plural': 'Übersicht',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ErrorAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.CharField(blank=True, default='Keine spezifische Beschreibung vorhanden', max_length=500, null=True, verbose_name='Beschreibung')),
                ('media', models.FileField(blank=True, default='error_appearances/coming-soon.png', null=True, upload_to='error_appearances/', verbose_name='Bild/Video')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Erstelldatum')),
                ('updated_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Änderungsdatum')),
            ],
            options={
                'verbose_name': 'Erscheinnungsbild',
                'verbose_name_plural': 'Erscheinungsbilder',
            },
        ),
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Import',
                'verbose_name_plural': 'Import',
            },
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('routemodel', models.FileField(blank=True, null=True, upload_to='routemodel/', verbose_name='Streckenmodell')),
                ('currently_active', models.BooleanField(default=False, verbose_name='Aktiv')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Erstelldatum')),
                ('updated_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Änderungsdatum')),
            ],
            options={
                'verbose_name': 'Instanz',
                'verbose_name_plural': 'Instanzen',
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.CharField(blank=True, default='Keine spezifische Beschreibung vorhanden', max_length=500, null=True, verbose_name='Beschreibung')),
                ('media', models.FileField(blank=True, default='solutions/coming-soon.png', null=True, upload_to='solutions/', verbose_name='Bild/Video')),
                ('rating', models.IntegerField(default=0, verbose_name='Rating')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Erstelldatum')),
                ('updated_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Änderungsdatum')),
                ('error_appearance', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='user_site.errorappearance', verbose_name='Erscheinungsbild')),
            ],
            options={
                'verbose_name': 'Lösung',
                'verbose_name_plural': 'Lösungen',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.CharField(blank=True, default='Keine spezifische Beschreibung vorhanden', max_length=500, null=True, verbose_name='Beschreibung')),
                ('pdf_document', models.FileField(blank=True, null=True, upload_to='locations/', verbose_name='PDF Dokument')),
                ('routemodel_coords', models.CharField(blank=True, max_length=200, null=True, verbose_name='Streckenmodel Koordinaten')),
                ('routemodel_pdf_coords', models.CharField(blank=True, max_length=200, null=True, verbose_name='Streckenmodel PDF Koordinaten')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Erstelldatum')),
                ('updated_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Änderungsdatum')),
                ('instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_site.instance', verbose_name='Instanz')),
            ],
            options={
                'verbose_name': 'Fehlerort',
                'verbose_name_plural': 'Fehlerorte',
            },
        ),
        migrations.CreateModel(
            name='ErrorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.CharField(blank=True, default='Keine spezifische Beschreibung vorhanden', max_length=500, null=True, verbose_name='Beschreibung')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Erstelldatum')),
                ('updated_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Änderungsdatum')),
                ('instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_site.instance', verbose_name='Instanz')),
            ],
            options={
                'verbose_name': 'Fehlerkategorie',
                'verbose_name_plural': 'Fehlerkategorien',
            },
        ),
        migrations.AddField(
            model_name='errorappearance',
            name='error_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='user_site.errorcategory', verbose_name='Fehlerkategorie'),
        ),
        migrations.AddField(
            model_name='errorappearance',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_site.location', verbose_name='Fehlerort'),
        ),
    ]
