# Generated by Django 3.2.6 on 2021-11-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='image_map',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Image-Map'),
        ),
    ]
