# Generated by Django 3.2.6 on 2021-11-22 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0003_alter_instance_routemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='routemodel_coords',
        ),
        migrations.RemoveField(
            model_name='location',
            name='routemodel_pdf_coords',
        ),
    ]
