# Generated by Django 3.2.6 on 2021-12-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0004_auto_20211122_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errorappearance',
            name='location',
        ),
        migrations.AddField(
            model_name='errorappearance',
            name='locations',
            field=models.ManyToManyField(to='user_site.Location', verbose_name='Fehlerort'),
        ),
        migrations.AlterField(
            model_name='errorappearance',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='errorcategory',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Beschreibung'),
        ),
    ]
