# Generated by Django 3.2.6 on 2022-02-21 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0006_auto_20211223_1453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solution',
            options={'verbose_name': 'Lösungsmaßnahme', 'verbose_name_plural': 'Lösungensmaßnahmen'},
        ),
    ]
