# Generated by Django 3.2.6 on 2022-03-01 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0008_alter_solution_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='completeerror',
            options={'managed': False, 'verbose_name': 'Overview', 'verbose_name_plural': 'Overviews'},
        ),
        migrations.AlterModelOptions(
            name='errorappearance',
            options={'verbose_name': 'Error appearance', 'verbose_name_plural': 'Error appearances'},
        ),
        migrations.AlterModelOptions(
            name='errorcategory',
            options={'verbose_name': 'Error category', 'verbose_name_plural': 'Error categories'},
        ),
        migrations.AlterModelOptions(
            name='instance',
            options={'verbose_name': 'Instance', 'verbose_name_plural': 'Instances'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='solution',
            options={'verbose_name': 'Solution', 'verbose_name_plural': 'Solutions'},
        ),
        migrations.AlterField(
            model_name='errorappearance',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='errorappearance',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='errorappearance',
            name='error_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='user_site.errorcategory', verbose_name='Error category'),
        ),
        migrations.AlterField(
            model_name='errorappearance',
            name='locations',
            field=models.ManyToManyField(to='user_site.Location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='errorappearance',
            name='media',
            field=models.FileField(blank=True, default='error_appearances/coming-soon.png', null=True, upload_to='error_appearances/', verbose_name='Image/Video'),
        ),
        migrations.AlterField(
            model_name='errorappearance',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Changed date'),
        ),
        migrations.AlterField(
            model_name='errorcategory',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='errorcategory',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='errorcategory',
            name='instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_site.instance', verbose_name='Instance'),
        ),
        migrations.AlterField(
            model_name='errorcategory',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Changed date'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='currently_active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='routemodel',
            field=models.ImageField(blank=True, null=True, upload_to='routemodel/', verbose_name='Routemodel'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Changed date'),
        ),
        migrations.AlterField(
            model_name='location',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='location',
            name='instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_site.instance', verbose_name='Instance'),
        ),
        migrations.AlterField(
            model_name='location',
            name='pdf_document',
            field=models.FileField(blank=True, null=True, upload_to='locations/', verbose_name='PDF document'),
        ),
        migrations.AlterField(
            model_name='location',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Changed date'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='error_appearance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='user_site.errorappearance', verbose_name='Error appearance'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='media',
            field=models.FileField(blank=True, default='solutions/coming-soon.png', null=True, upload_to='solutions/', verbose_name='Image/Video'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Changed date'),
        ),
    ]
