# Generated by Django 3.2.6 on 2022-01-05 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_site', '0006_auto_20211223_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_appearance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_site.errorappearance', verbose_name='Erscheinungsbild')),
            ],
            options={
                'verbose_name': 'Cluster',
                'verbose_name_plural': 'Cluster',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='', max_length=5000, verbose_name='Inhalt')),
            ],
            options={
                'verbose_name': 'Kommentar',
                'verbose_name_plural': 'Kommentare',
            },
        ),
        migrations.CreateModel(
            name='MainObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='', max_length=5000, verbose_name='Text')),
                ('lemma', models.TextField(default='', max_length=5000, verbose_name='Lemma')),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nlp_component.cluster', verbose_name='Cluster')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='', max_length=5000, verbose_name='Text')),
                ('lemma', models.TextField(default='', max_length=5000, verbose_name='Lemma')),
                ('main_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nlp_component.mainobject', verbose_name='Kernobjekt')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='', max_length=5000, verbose_name='Text')),
                ('lemma', models.TextField(default='', max_length=5000, verbose_name='Lemma')),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nlp_component.cluster', verbose_name='Cluster')),
            ],
        ),
        migrations.CreateModel(
            name='Addition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='', max_length=5000, verbose_name='Text')),
                ('lemma', models.TextField(default='', max_length=5000, verbose_name='Lemma')),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nlp_component.cluster', verbose_name='Cluster')),
            ],
        ),
        migrations.CreateModel(
            name='RequestComment',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nlp_component.comment')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Erstelldatum')),
                ('error_appearance', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='user_site.errorappearance', verbose_name='Erscheinungsbild')),
            ],
            options={
                'verbose_name': 'Neuer Lösungsvorschlag',
                'verbose_name_plural': 'Neue Lösungsvorschläge',
            },
            bases=('nlp_component.comment', models.Model),
        ),
        migrations.AddField(
            model_name='cluster',
            name='comments',
            field=models.ManyToManyField(to='nlp_component.RequestComment', verbose_name='Lösungsvorschlag'),
        ),
    ]
