# Generated by Django 3.2.6 on 2022-02-21 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nlp_component', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cluster',
            options={'verbose_name': 'Gruppe', 'verbose_name_plural': 'Gruppen'},
        ),
    ]
