# Generated by Django 3.2.6 on 2022-02-21 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp_component', '0002_alter_cluster_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lemma', models.TextField(default='', max_length=5000, verbose_name='Lemma')),
            ],
            options={
                'verbose_name': 'Gruppe',
                'verbose_name_plural': 'Gruppen',
            },
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='', max_length=5000, verbose_name='Lemma')),
            ],
            options={
                'verbose_name': 'Gruppe',
                'verbose_name_plural': 'Gruppen',
            },
        ),
        migrations.AddField(
            model_name='cluster',
            name='sentenced',
            field=models.TextField(default='', max_length=5000, verbose_name='Lemma'),
        ),
    ]
