# Generated by Django 3.2.6 on 2022-02-21 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nlp_component', '0003_auto_20220221_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='sentenced',
        ),
    ]
