# Generated by Django 3.2.6 on 2022-02-21 22:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp_component', '0004_remove_cluster_sentenced'),
    ]

    operations = [
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0.7, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(1.0)], verbose_name='Wert')),
            ],
            options={
                'verbose_name': 'Ähnlichkeitsschwellenwert',
                'verbose_name_plural': 'Ähnlichkeitsschwellenwert',
            },
        ),
        migrations.AlterField(
            model_name='cluster',
            name='comments',
            field=models.ManyToManyField(to='nlp_component.RequestComment', verbose_name='Lösungsvorschläge'),
        ),
    ]
