# Generated by Django 3.2.6 on 2022-02-24 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nlp_component', '0006_auto_20220224_2052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyword',
            options={'verbose_name': 'Schlüsselwort', 'verbose_name_plural': 'Schlüsselwörter'},
        ),
        migrations.AlterModelOptions(
            name='sentence',
            options={'verbose_name': 'Satz', 'verbose_name_plural': 'Sätze'},
        ),
    ]
