# Generated by Django 3.2.6 on 2022-02-25 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0008_alter_solution_options'),
        ('nlp_component', '0007_auto_20220224_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='error_appearance',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='user_site.errorappearance', verbose_name='Erscheinungsbild'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='content',
            field=models.TextField(default='', max_length=5000, verbose_name='Satz'),
        ),
    ]
