# Generated by Django 3.2.6 on 2022-02-25 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nlp_component', '0008_auto_20220225_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='name',
            field=models.TextField(default='', max_length=5000, verbose_name='Satz'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='content',
            field=models.TextField(default='', max_length=5000, verbose_name='Inhalt'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nlp_component.group', verbose_name='Gruppe'),
        ),
    ]
