# Generated by Django 3.2.6 on 2022-03-01 01:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_site', '0009_auto_20220301_0220'),
        ('nlp_component', '0009_auto_20220225_0200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyword',
            options={'verbose_name': 'Keyword', 'verbose_name_plural': 'Keywords'},
        ),
        migrations.AlterModelOptions(
            name='sentence',
            options={'verbose_name': 'Sentence', 'verbose_name_plural': 'Sentences'},
        ),
        migrations.AlterModelOptions(
            name='threshold',
            options={'verbose_name': 'Similarity threshold', 'verbose_name_plural': 'Similarity thresholds'},
        ),
        migrations.AlterModelOptions(
            name='usercomment',
            options={'verbose_name': 'New user comment', 'verbose_name_plural': 'New user comments'},
        ),
        migrations.AlterField(
            model_name='keyword',
            name='sentence',
            field=models.ManyToManyField(to='nlp_component.Sentence', verbose_name='Sentence'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='content',
            field=models.TextField(default='', max_length=5000, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='name',
            field=models.TextField(default='', max_length=5000, verbose_name='Sentence'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='user_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nlp_component.usercomment', verbose_name='User comment'),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='value',
            field=models.FloatField(default=0.7, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(1.0)], verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='usercomment',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='create date'),
        ),
        migrations.AlterField(
            model_name='usercomment',
            name='error_appearance',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='user_site.errorappearance', verbose_name='Error appearance'),
        ),
        migrations.CreateModel(
            name='CommentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_appearance', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='user_site.errorappearance', verbose_name='Error appearance')),
            ],
            options={
                'verbose_name': 'Group of user comments',
                'verbose_name_plural': 'Groups of user comments',
            },
        ),
        migrations.AlterField(
            model_name='sentence',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nlp_component.commentgroup', verbose_name='Group'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
